### ISSUE TITLE
Error: object is not a function

### ISSUE THREAD

**Issue by sshinde** [neoziro/angular-notification#3]
Hi, I am trying to use your code as is however when I click the notification it throws the following error:
```javascript
TypeError: object is not a function
    at NgNotification.<anonymous> (angular-notification.js:64)
    at angular-notification.js:106
    at l.$get.l.$eval (angular.js:14383)
    at l.$get.l.$apply (angular.js:14482)
    at Notification.applyListener (angular-notification.js:105)
```

The issue is that the call $window.focus() is failing. Any idea why?
```javascript
       // Focus window on click.
        if (options.focusWindowOnClick) {
            self.$on('click', function () {
              $window.focus();
            });
        }
```

**A few more questions:**
1. If multiple tabs are opened in the browser I would like to take the user to the respective tab. How to achieve that?
2. I would like to pass a custom "tag" to the notification and expect it to pass it back to me when the user clicks it. How do I achieve that?

Thanks in advance

**Comment by neoziro** [comment]
Hi, to be honest with you I don't remember the answer of your questions. This module is just a wrapper around the Notification API of the browser. I think you should refer to [the official documentation](https://developer.mozilla.org/en/docs/Web/API/notification) in order to find the answer to your questions.

1. I think the behaviour is not the same in every browser, you can do it in Chrome but not in Firefox.
2. Please refer to the documentation to do that.

Maybe `$window.focus` in not exposed by Angular? I don't know.
