### ISSUE TITLE
Should return immediately if Notification is not supported

### ISSUE THREAD

**Issue by CarterLi** [neoziro/angular-notification#8]
https://github.com/neoziro/angular-notification/blob/master/angular-notification.js#L131
This breaks IE ( and maybe other browsers which don't support WebNotifications )

**Comment by danieltheodosius** [comment]
May I know whether this has been resolved? I believe that the behaviour still happens because it still executes the next logic https://github.com/neoziro/angular-notification/blob/master/angular-notification.js#L136 even the window notification is undefined and it throws Error.

This happens on safari in iOS device. This force me to check $window.Notification to exists before I request for permission.

**Comment by neoziro** [comment]
@danieltheodosius the check is done on line 132-133 isn't it?

**Comment by danieltheodosius** [comment]
It is done on line 132-133, however the if statement only rejects it, not immediately return so it executes the next logic which requires to have the window notification.

**Comment by neoziro** [comment]
@danieltheodosius it's now fixed
